# Generated by Django 4.2.3 on 2023-07-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacionando', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='unidade_caixa',
            field=models.CharField(max_length=100),
        ),
    ]
