# Generated by Django 4.2.3 on 2023-07-20 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relacionando', '0002_alter_unidade_unidade_caixa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ods',
            old_name='nome',
            new_name='numero_oes',
        ),
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(max_length=100)),
                ('ods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relacionando.ods')),
            ],
        ),
    ]
